### ISSUE TITLE
Query BIGINT return Character not Int64

### ISSUE THREAD

**Issue by raymondyao** [s-u/RJDBC#107]
Is it on purpose that the query result from BIGINT is converted to Character not Int64?

**Comment by s-u** [comment]
There is no `Int64` in R, so `character` in the only R type which can hold the value without loss of precision. You can use `lossy=TRUE` if you are ok with 53-bit precision (fine if you really mean to use it as a large integer) or use type maps if you have a preferred other type you want to store the values as (see documentation and the `NEWS` file).

**Comment by raymondyao** [comment]
Thanks for the reply.
