### ISSUE TITLE
Non-vectorized dbSendUpdate right-pads STRING values

### ISSUE THREAD

**Issue by liudvikasakelis** [s-u/RJDBC#109]
As I only have access to Impala currently, this reprex is in Impala.
```
CREATE TABLE `airlines` (`carrier` STRING, `name` STRING); 
  
INSERT INTO `airlines` VALUES
  ('9E', 'Endeavor Air Inc.'),
  ('AA', 'American');
```
If I copy-paste this reprex straight into Impala Shell, then 
```
SELECT name FROM airlines WHERE carrier = "AA";
returns 
"American"
```
However, if I CREATE and INSERT using dbSendUpdate from R
```
getMethod(dbSendUpdate, c("JDBCConnection", "character"))(
  impala$con,
  "INSERT INTO `airlines` VALUES
  ('9E', 'Endeavor Air Inc.'),
  ('AA', 'American')"
)

> tbl(impala, "airlines") %>%
+   filter(carrier == "AA") %>%
+   select(name) %>%
+   pull(1)
+ [1] "American         "
```

(the result is left-padded when querying from Impala shell as well, so the problem is with inserting, not with the querying). 

Could this be caused by RJDBC? I'm going to spin up other RJDBC-supported databases to see if RJDBC is the common factor.

**Comment by s-u** [comment]
Impala seems to have been abandoned few years ago, so I can't spin up a docker test instance, but it looks like your DBMS may not be distinguishing between the type size and the string length, so it will always return the full size. Please note that RJDBC is just a front-end to whatever driver you are using (the query is just a pass-through as an opaque string sent to the driver, RJDBC doesn't interpret it), so it check the driver and your DBMS documentation on the types and expected behavior. 

I ran this test on MySQL and Postgres (see the `test.sh` script in RDJBC) with the same result (no padding):

```
MySQL = JDBC('org.mariadb.jdbc.Driver','mariadb-connector-java.jar',"`")
c = dbConnect(MySQL, "jdbc:mysql://localhost/test", user="test", password="test1234")
dbSendUpdate(c, "CREATE TABLE `airlines` (`carrier` VARCHAR(4), `name` VARCHAR(128));")
dbSendUpdate(c, "INSERT INTO `airlines` VALUES ('9E', 'Endeavor Air Inc.'), ('AA', 'American')")
str(dbGetQuery(c,"SELECT * FROM airlines;"))
## 'data.frame':	2 obs. of  2 variables:
##  $ carrier: chr  "9E" "AA"
##  $ name   : chr  "Endeavor Air Inc." "American"
```

```
PG = JDBC('org.postgresql.Driver','postgresql-connector.jar',"\"")
c = dbConnect(PG, "jdbc:postgresql://localhost/test", user="test", password="test1234")
dbSendUpdate(c, 'CREATE TABLE "airlines" ("carrier" VARCHAR(4), "name" VARCHAR(128));')
dbSendUpdate(c, "INSERT INTO airlines VALUES ('9E', 'Endeavor Air Inc.'), ('AA', 'American')")
str(dbGetQuery(c,"SELECT * FROM airlines;"))
## 'data.frame':	2 obs. of  2 variables:
##  $ carrier: chr  "9E" "AA"
##  $ name   : chr  "Endeavor Air Inc." "American"
```

**Comment by liudvikasakelis** [comment]
Thank you immensely for your quick response, not to mention for running 2 more test cases :bow: 
However I'm confident the DBMS itself can distinguish between type size and string length - from my examples, correct (unpadded) insertion is achieved by pasting the exact same string in Impala prompt.
So from your test results + the fact that RJDBC doesn't modify the query, I agree it's probably not RJDBC. 
I think it's likely that JDBC driver itself is buggy? (Cloudera Impala 4.0, 4.1 and 4.2 tested all with same bug for anyone with same problem).

**Comment by liudvikasakelis** [comment]
Semi-confirmed that my JDBC drivers are dodgy by using them in a Python script, where sending an INSERT statement showed the same bug :( Thank you for your insights!
