### ISSUE TITLE
Replace use of call to representation() from setClass

### ISSUE THREAD

**Issue by imanuelcostigan** [s-u/RJDBC#16]
This was deprecated in R 3.0.0. See `?setClass`

**Comment by imanuelcostigan** [comment]
This might (i.e. this is unconfirmed) be causing RJDBC to return `FALSE` to `inherits(con, "DBIConnection")` while `inherits(con, "JDBCConnection")` is `TRUE`

**Comment by s-u** [comment]
I don't see an issue here, this sounds more like a user error - `inherits()` is the wrong check to use since it only checks the most specialized class - for S4 objects you have to use `is()` if you want to take inheritance into account:

```r
> c<-dbConnect(MySQL, "jdbc:mysql://localhost/test")
> is(c,"DBIConnection")
[1] TRUE
```
