### ISSUE TITLE
insert into statements using dbGetQuery

### ISSUE THREAD

**Issue by karthikg0703** [s-u/RJDBC#23]
Currently, insert into doesn't work with dbGetQuery, as it doesn't return any results. Could we get a fix for this ?

**Comment by imanuelcostigan** [comment]
@karthikg0703 dbSendUpdate is what you want to use.

**Comment by karthikg0703** [comment]
@imanuelcostigan dbSendUpdate somehow doesn't work when I do an insert into - I'm using Impala, and it's not inserting the rows. When I try running the exact same code manually, its inserting the data. Further, because it doesn't return any result, I'm not sure if its failing silently

**Comment by imanuelcostigan** [comment]
@karthikg0703 it worked for SQL Server https://github.com/imanuelcostigan/RSQLServer/blob/a6f2ed0396ec80704a92f4eee709858c89d259de/R/dbi-methods.R#L285

**Comment by karthikg0703** [comment]
@imanuelcostigan I tried running it with dbSendUpdate, and figured what's happening. As soon as we call the function, it returns immediately and I assume its done running the query, but in theory, its still running the code in the backend. So if I run a loop where I'm inserting weekly data for say 2 months, I get a response that its successful, but when I manually do a max(dt) on the table, it doesn't show that the table is updated yet.. Is there any way you can make dbSendUpdate return some sort of message from the DB that the action is succesful?

**Comment by imanuelcostigan** [comment]
The method will return an error if it hasn't succeeded. My guess is that this isn't an RJDBC bug.
