### ISSUE TITLE
Check if connection is active

### ISSUE THREAD

**Issue by lc0** [s-u/RJDBC#24]
Hi guys,

first of all, thanks for your package! I was using another package - **pingles/redshift-r** that is based on your package. So my question is there a way to check if connections still active?

R's DBI supports it with *dbIsValid* or deprecated *isIdCurrent*
Is there a way to do it properly with your package?

cc @pingles

**Comment by s-u** [comment]
There is no such thing - the handle is always valid, that's all JDBC knows. The driver may choose not to hold a connection at all. As far as JDBC is concerned it doesn't matter. You can always run a query to find out if the DBMS still reacts, e.g. some people use trivial queries like `dbSendQuery("SELECT 1")`.
