### ISSUE TITLE
hive jdbc execute vs executeQuery

### ISSUE THREAD

**Issue by piccolbo** [s-u/RJDBC#25]
Hi 
I am using RJDBC to connect to a HIVE JDBC server. Create statements fail. I found that RJDBC prepares a create statement and then calls executeQuery on it. Tracking down forum discussion, I found out that it used to work, but it's become more strict and that now one is supposed to call execute to create tables, which returns a boolean. I verified that's the case with

```
.jcall(s, "Z", "execute", as.character(statement)[1],  check = TRUE)
[1] TRUE
```

It's not clear to me that this is a RJDBC bug, but for them it is an "improvement" and I see it as unlikely they are going to backtrack. What's the way forward? Thanks

**Comment by s-u** [comment]
This seems like a user error - `executeQuery` is only called by `dbSendQuery()`, but a DDL statement is not a query, so the user should have called `dbSendUpdate()` instead. Can you confirm that `dbSendUpdate()` works in that context as designed?

**Comment by piccolbo** [comment]
Yes it does. One clarification is that I came here through dplyr::db_create_table and DBI::dbSendQuery, so I need to check with them why they use sendQuery. The other thing is that  I am looking at the sendQuery method and I see this code

```
        else {
            s <- .jcall(conn@jc, "Ljava/sql/Statement;", "createStatement")
            .verify.JDBC.result(s, "Unable to create simple JDBC statement ", 
                statement)
            r <- .jcall(s, "Ljava/sql/ResultSet;", "executeQuery", 
                as.character(statement)[1], check = FALSE)
            .verify.JDBC.result(r, "Unable to retrieve JDBC result set for ", 
                statement)
```
To me that looks like a special case for a create statement, so if sendQuery is not the right call to create tables, why is the special case there?

**Comment by s-u** [comment]
That branch is for queries w/o additional arguments (i.e., no `?` substitution) - `createStatement` is just a method in Java to create a statement object, regardless of the type of the statement.

**Comment by piccolbo** [comment]
Doh, it all makes sense now, thanks.
