### ISSUE TITLE
dbWriteTable doesn't allow specification of schema

### ISSUE THREAD

**Issue by abeburnett** [s-u/RJDBC#27]
I'm running into an issue because I'm unable to fully qualify a table name to include the schema. I.e., the user's default schema is 'dbo' but the schema of the desired table to write to is 'AB.' When I include the schema as part of the table name (e.g., 'AB.My_Table') it doesn't find the table. 

Is there a work around? Ideally I'd like to be able to specify the schema of the table in the call to dbWriteTable. Is this possible?

**Comment by karillo** [comment]
This is likely a consequence of #5 - there was a request back in January for examples to test against, but none have been supplied.

**Comment by s-u** [comment]
Getting the existence checks work on this seem too fragile, so I have added `force=TRUE` option which skips the existence check and allows `dbWriteTable()` to insert into non-tables. However, it means it can fail if the target doesn't exist or doesn't match.
