### ISSUE TITLE
dbListTables only shows system tables

### ISSUE THREAD

**Issue by abeburnett** [s-u/RJDBC#28]
This is very odd because when I log into the server directly (through Management Studio), using the same username and password, I can see all the tables I need... But when I connect via RJDBC I only see the system tables.

Any ideas why? Is this a bug in the driver or is there anything on the permissions side which can cause this issue?

**Comment by karillo** [comment]
This also is likely a consequence of #5

**Comment by s-u** [comment]
see #34
