### ISSUE TITLE
dbSendUpdate requires a row count

### ISSUE THREAD

**Issue by russellpierce** [s-u/RJDBC#29]
I would like to use Hive environmental variables to leverage the value of views within Hive and to set the priority of my Hive queries.  The way I've seen to do this is in the form of the command `set mapred.job.priority=VERY_LOW`.

I connect to Hive and generate my queries at run-time via `RJDBC`.  When I use `dbSendUpdate` to send the command above I receive the following error message:

```
execute JDBC update query failed in dbSendUpdate ([Simba][JDBC](11320) A RowCount was expected but not generated from query "set mapred.job.priority=VERY_LOW". Query not executed. )
```

Is there a way to send these environmental variable setting commands to Hive via `RJDBC`?  Should dbSendUpdate require a RowCount, can it be made optional?  Is this a flaw in the JDBC driver being used or the package `RJDBC`?

**Details and versions:**
- I'm using Amazon's HIVE drivers to connect to a EMR Release 4.1 cluster on AWS
- Hive 1.0.0
- R Version 3.2.2
- RJDBC version 0.2-5
- DBI version 0.3.1

Also here: http://stackoverflow.com/questions/33038879/how-can-one-update-environmental-variables-in-hive-from-r

**Comment by s-u** [comment]
That looks like a bug in the driver - the whole point of `dbSendUpdate()` is that it does *not* require a result set.
