### ISSUE TITLE
Passing additional parameters to dbConnect function for JDBCDriver in R

### ISSUE THREAD

**Issue by MarcinKosinski** [s-u/RJDBC#31]
Could you pleas provide some explanation on 
http://stackoverflow.com/questions/34861844/passing-additional-parameters-to-dbconnect-function-for-jdbcdriver-in-r?noredirect=1#comment57470540_34861844

**Comment by s-u** [comment]
Links are useless, so to rephrase the question - "what parameters can be passed to `dbConnect`"?

Simply anything - all that `dbConnect` does is to collect whatever you pass (including `...`) and collect it all into a property dictionary (`java.util.Properties`) that is passed to the driver's `connect()` method. So any named argument you pass is included. So the only special argument is `url` which is passed directly, everything else is included in the properties. How that gets interpreted is out of RJDBC's hands - it's entirely up to the driver.

**Comment by MarcinKosinski** [comment]
Thanks for explanation.

2016-01-22 15:28 GMT+01:00 Simon Urbanek <notifications@github.com>:
