### ISSUE TITLE
Non-informative error messages

### ISSUE THREAD

**Issue by hhoeflin** [s-u/RJDBC#32]
In my projects, R using RJDBC returns very cryptic error messages. Using the same jar as RJDBC, but using SQLWorkbench, error messages are considerably more informative. 

Though I was thinking that the error information is passed back by the server, but not collected by RJDBC? Could this be improved? Would be very helpful for debugging larger queries (as are produced, by dplyr)

**Comment by s-u** [comment]
Can you provide details? E.g., the output of the same error in SQLWorkbench and JDBC as to illustrate what you are asking for?

**Comment by hhoeflin** [comment]
Great that you asked. The issue seems to be the following:
The same error message that SQLWorkbench produces is also in the R error message - but at the end. And R often truncates an error message if it is too long - deleting the informative part of the error that is at the end.

So, would it be possible to truncate the error message RJDBC throws in a way that the SQL in the middle truncated but the informative part of the error at the end is still there?

SQLWorkbench error message (edited):
An error occurred when executing the SQL command:
< ... some SQL query ...  truncated>

[Vertica][VJDBC](3429) ERROR: For 'isnull', types numeric and varchar are inconsistent
  [Vertica][VJDBC]Detail: Columns: unknown and unknown [SQL State=42804, DB Errorcode=3429]


R error message (edited):
Error in .verify.JDBC.result(r, "Unable to retrieve JDBC result set for ",  
  Unable to retrieve JDBC result set for 
< some long SQL query, not truncated> 
([Vertica][VJDBC](3429) ERROR: For 'isnull', types numeric and varchar are inconsistent
  [Vertica][VJDBC]Detail: Columns: unknown and unknown)

**Comment by coodgee** [comment]
I have this same problem. If the sql string is long then the informative part of the error message is lost because the error string is truncated. Was a solution ever found to this? Is it possible to save the error string somewhere without it being truncated?

**Comment by MichaelChirico** [comment]
See here for some more options:

https://stackoverflow.com/a/50387968/3576984

However, for extra-long queries, setting `options('warning.length')` won't fully address the issue raised here. It might be helpful if `RJDBC` could do one of two things:

 1. Put the diagnostic part of the error message first -- that way, if there's forced truncation, it will be the query that's truncated, not the diagnostic
 2. Internally truncate the verbatim query reproduction that's printed out (`Unable to retrieve JDBC result set for select <truncated bit> <diagnostic message>`)

I've raised the issue of forced-truncation at length 8190 to `r-devel`, will post the thread link when I get a chance.

**Comment by Cobaltikus** [comment]
Another possible alternative (maybe?):
3. Expose the max length property that is used to determine when text is too long and must be truncated, such that the truncation could be avoided given an appropriately large value.

**Comment by dernst** [comment]
@MichaelChirico as for `RJDBC` can't you get the full message if you do something like this:
```
xx = try(dbGetQuery(conn, "SELECT bar FROM foo"))
ex = attr(xx, "condition")
cat(ex$message, "\n")
```

**Comment by s-u** [comment]
Thanks, I have changed the output format to include a) RDJBC error, b) JDBC Jqva error, c) the statement so instead

```
Error in .verify.JDBC.result(r, "Unable to retrieve JDBC result set for ",  : 
  Unable to retrieve JDBC result set for SELECT Species as Kind, count(Species) as Count FROM iris WHERE `Sepal.Width` > ? GROUP BY Species ((conn=56) Table 'test.iris' doesn't exist)
```

it is now

```Error in .verify.JDBC.result(r, "Unable to retrieve JDBC result set",  : 
  Unable to retrieve JDBC result set
  JDBC ERROR: (conn=58) Table 'test.iris' doesn't exist
  Statement: SELECT Species as Kind, count(Species) as Count FROM iris WHERE `Sepal.Width` > ? GROUP BY Species
```
