### ISSUE TITLE
Can't connect to specific databse when connecting with HiveServer2

### ISSUE THREAD

**Issue by MarcinKosinski** [s-u/RJDBC#34]
`RJDBC` is a great tool for R users that are not so familiar with `Java` and `JDBC` drivers and provides a friendly interface to databases such as `HiveServer2`. Thank's for your work on that package.

I've been recently using `RJDBC` to connect to `HiveServer2`. I've learned it from  @piccolbo who has implemented a dplyr frontend to `JDBC` connecting with `HiveServer2` (https://github.com/rzilla/dplyr.spark.hive/tree/master/pkg). The following code enables me to create a `JDBCDriver` that uses `org.apache.hive.jdbc.HiveDriver` driverClass to connect with `HiveServer2`:

````{R}
dbConnect(drv = 
            JDBC(driverClass = "org.apache.hive.jdbc.HiveDriver",
                 classPath = c("/opt/hive/lib/hive-jdbc-1.0.0-standalone.jar",
                               "/usr/share/hadoop/share/hadoop/common/lib/commons-configuration-1.6.jar",
                               "/usr/share/hadoop/share/hadoop/common/hadoop-common-2.4.1.jar")), 
          url = paste0("jdbc:hive2://",
                       host = 'tools-1.hadoop.srv', ":",
                       port = 10000,
                       "/loghost;auth=noSasl"),
          username = "mkosinski") -> conn

dbGetQuery(conn, "SHOW DATABASES")[1,1] -> db1
dbGetQuery(conn, "SHOW DATABASES")[2,1] -> db2
dbGetQuery(conn, "SHOW DATABASES")[3,1] -> db3
dbGetQuery(conn, "SHOW DATABASES")[4,1] -> db4
````

The `SHOW DATABASES`  statement lists all databases that are available in the `HiveServer2`.  So the `db1`, `db2`, `db3` and `db4` are 4 various names of existing databases that one can connect to. I've tried such code to list all available tables in each database

````{R}
listTablesInDatabase <- function(dbname){

  dbConnect(drv = 
              JDBC(driverClass = "org.apache.hive.jdbc.HiveDriver",
                   classPath = c("/opt/hive/lib/hive-jdbc-1.0.0-standalone.jar",
                                 "/usr/share/hadoop/share/hadoop/common/lib/commons-configuration-1.6.jar",
                                 "/usr/share/hadoop/share/hadoop/common/hadoop-common-2.4.1.jar")), 
            url = paste0("jdbc:hive2://",
                         host = 'tools-1.hadoop.srv', ":",
                         port = 10000,
                         "/", dbname, ";auth=noSasl"),
            username = "mkosinski") -> conn
  dbListTables(conn)

}
````

but it looks  like all connections return the same number of tables 

````{R}
> length(listTablesInDatabase(db1))
[1] 1420
> length(listTablesInDatabase(db2))
[1] 1420
> length(listTablesInDatabase(db3))
[1] 1420
> length(listTablesInDatabase(db4))
[1] 1420
````

to be  more specific - those are all tables in all databases :| 

So my question is how one can specify the database name to connect to specific database instead of all databases? Do you think this is the matter of `RJDBC` or `HiveServer2`?

@karillo do you thinks this is the matter of #5 #27 #28  ?

**Comment by sz-cgt** [comment]
The Hive JDBC drivers deliberately make all schemas available to you.  All you can specify in the connection URL is the **default** database.

The issue is actually with the dbGetTables/dbListTables functions using a schema value of NULL in the GetTables JDBC command.

Changing dbGetTables as follows will give you what you want:

    setMethod("dbGetTables", "JDBCConnection", def=function(conn, table="%", schema='%', ...) {
      md <- .jcall(conn@jc, "Ljava/sql/DatabaseMetaData;", "getMetaData", check=FALSE)
      .verify.JDBC.result(md, "Unable to retrieve JDBC database metadata")
      r <- .jcall(md, "Ljava/sql/ResultSet;", "getTables", .jnull("java/lang/String"),
              schema, table, .jnull("[Ljava/lang/String;"), check=FALSE)
      .verify.JDBC.result(r, "Unable to retrieve JDBC tables list")
      on.exit(.jcall(r, "V", "close"))
      .fetch.result(r)
    })

then just specify a name or a pattern for the schema.  As a bonus, this also works on Postgres.

**Comment by MarcinKosinski** [comment]
Thanks for the reply. I'll check that ASAp :)

Marcin Kosinski

Dnia 02.06.2016 o godz. 18:29 Stephen <notifications@github.com> napisał(a):

**Comment by Mkkl91** [comment]
I get an "Error in .local(conn, ...)  could not find function ".verify.JDBC.result" " message when trying to redefine the function...

**Comment by s-u** [comment]
You'll need to either prefix it with `RDJBC:::` or run something like
```
.verify.JDBC.result <- RJDBC:::.verify.JDBC.result
.fetch.result <- RDJBC:::.fetch.result
```
as those are internal and thus not exported.

**Comment by s-u** [comment]
I have added the proposed `schema=` argument to `dbListTables()` and `dbGetTables()` - with the default being `NULL`, so using according to the above `schema="%"` should work without modifying RJDBC.

**Comment by filipwastberg** [comment]
I think it would be useful to update the documentation to specify that `schema` is possible to specify? Had to search the whole world wide web to find this.

**Comment by JonWayland** [comment]
Is there a similar option for creating/inserting to tables in a specified schema?

**Comment by chsafouane** [comment]
Is it possible to add the parameter `schema` to the function dbExistsTable ?
