### ISSUE TITLE
dbConnect(..) fails for Hypersonic/HSQLDB with (1) space in url, and/or (2) empty password

### ISSUE THREAD

**Issue by krevelen** [s-u/RJDBC#46]
I can create a HSQLDB database in my Windows file system using the default empty password and spaces in the path, e.g. using the URL `"jdbc:hsqldb:file:C:/with space/mydb"`, with (default) username `"SA"` and empty password `""`. RJDBC however will throw on both occasions:

```
Error in .jcall(drv@jdrv, "Ljava/sql/Connection;", "connect", as.character(url)[1],  : 
  java.sql.SQLInvalidAuthorizationSpecException: invalid authorization specification
```

For now, as a work-around I do the following:

- encode the URL myself, i.e. ` ` (space) becomes `%20`
- specify password `"SA"` (anything else I try fails)

Yielding for example:

```
require('RJDBC')
drv <- JDBC( driverClass="org.hsqldb.jdbc.JDBCDriver", classPath="C:/path/to/hsqldb-2.3.4.jar")
conn <- dbConnect(drv, "jdbc:hsqldb:file:C:/with%20space/mydb", "SA", "SA")
```

**Comment by s-u** [comment]
Note that this is really up to the driver and has nothing to do with RJDBC.  I'll close it but will keep it for people that may search it.

**Comment by krevelen** [comment]
Hi Simon,

Sorry to bother you but I think the empty password is an RJDBC problem, as
the error reproduces in Java if the password is null, but I'm providing
RJDBC::dbConnect with an empty character vector/string, not null. I suspect
somewhere along the line the empty string in R is replaced by NULL (R) or
null (Java), what do you think?

Cheers,
Rick
