### ISSUE TITLE
Error while retrieving more than 10 records from OSI PI throuh rjdbc

### ISSUE THREAD

**Issue by hissanruhma** [s-u/RJDBC#48]
I am trying to fetch data from OSI PI through R. I am using PIJDBC driver and RJDBC package.However when I try to get data(more than 10 records) using dbGetquery function I am getting the following error:
 Error in .jcall(rp, "I", "fetch", as.integer(n), block) : 
 java.sql.SQLException: java.lang.ArrayIndexOutOfBoundsException: 10

 it is working fine for less than 10 records.

Any help pls

**Comment by s-u** [comment]
This is likely outdated, but if you still have issues, please supply full reproducible example.
