### ISSUE TITLE
dbListTables() lacks schema handling

### ISSUE THREAD

**Issue by karillo** [s-u/RJDBC#5]
`dbListTables()` returns a single vector of table names in the database without identifying the schema associated with the table.

Losing this intermediary level of hierarchy has a number of impacts:
- A table name which exists in multiple schemas in the same database will return `TRUE` for `dbExistsTable()` even if it does not exist in the target schema - (assuming we restrict our internal scope and target to a default schema and avoid any explicit references to schema).
- A table name, qualified with its schema will always return `FALSE` for `dbExistsTable()`
- `dbWriteTable()` will fail when attempting `append=TRUE` or `overwrite=TRUE` and specifying a schema-specific  `name="[schema].[table]"` (as a direct consequence of `dbExistsTable()` failing with a qualified name).

It's likely there are other downstream consequences stemming from this behavior.

I'm not sure I know the strategy I'd prefer for resolution. Adding `schema=NA` as a default to most commands and passing it accordingly may be a useful strategy, though it _is_ tempting to want to use standard `"[schema].[table]"` (or even `"[database].[schema].[table]"`) dot notation directly.

**Comment by mattpolicastro** [comment]
I would also like to see this added. Debate over using schema with similar/identical tables aside, RJDBC access is largely meaningless when I'm unable to identify specific tables—even with dot notation.

**Comment by s-u** [comment]
@mattpolicastro can you elaborate? AFAICS this issue is about listing available tables - it doesn't affect queries or access to tables/views - you can always use the full power of the SQL syntax for your database, but maybe I'm misunderstanding the issue here.

**Comment by mattpolicastro** [comment]
Without getting into the nitty-gritty, the database I'm working with has a fairly complex/large set of schema based on past architectural decisions. Yes, SQL syntax works well, but I would argue that missing schema data results in frequent "query -> result" loops when I would much rather subset, filter, and modify data inside R itself. I suppose it's ultimately a matter of preference, but I suspect it would be a major boon for users less familiar with SQL.

**Comment by s-u** [comment]
I see, ok, I'll look into it. Do you have some test example I could use? I.e., what openly available database supports schemas in the way that we need to test?

**Comment by mattpolicastro** [comment]
Apologies for the prolonged silence—I've been looking for publicly-available samples similar to what I'm dealing with and have been unsuccessful so far. I'll keep looking.

**Comment by krlmlr** [comment]
Schema support is planned in DBI: https://github.com/rstats-db/DBI/issues/24#issuecomment-171438965.

**Comment by sz-cgt** [comment]
You can use Postgres to test this.  The issue is not setting schemaPattern to a value in the getTables JDBC command.

See my fix in #34

**Comment by s-u** [comment]
see #34
