### ISSUE TITLE
Issue with type conversion and SMALLINT on DB/2

### ISSUE THREAD

**Issue by s-fleck** [s-u/RJDBC#52]
I get the following error when I try to write a table with an integer column that contains `NA` values to a `SMALLINT` field in am existing **DB2** table using `dbWriteTable()`:

```
Error in .local(conn, statement, ...) : 
  execute JDBC update query failed in dbSendUpdate ([jcc][10177][11584][3.69.24] Invalid data conversion: Requested conversion would result in a loss of precision of -2147483648. ERRORCODE=-4461, SQLSTATE=42815)
```
The Issue does only occur for `data.frames` with more than one row.
The issues does not not occur if I convert the integer column to `character` first (or remove all NAs). 

To me it looks like it is trying to encode the NA values as -2147483648 (which I guess would be the appropriate value for INTEGER but not SMALLINT?)

In a similliar fashion, I get the following error message when using `dbWriteTable()` to save a `data.frame` that contains a column with only `NA`  values to a DOUBLE field in an existing DB2 table:

```
Error in .local(conn, statement, ...) : 
  execute JDBC update query failed in dbSendUpdate ([jcc][t4][102][10040][3.69.24] Batch failure.  The batch was submitted, but at least one exception occurred on an individual member of the batch.
Use getNextException() to retrieve the exceptions for specific batched elements. ERRORCODE=-4229, SQLSTATE=null)
```

Both issues occur in RJDBC 0.2.7, but RJDBC 0.2.5 seems fine.

**Comment by s-fleck** [comment]
It seems writing `NA`s/`NULL`s is broken for some other data types as well

**Comment by s-u** [comment]
Is this now resolved by #78 ?

**Comment by s-fleck** [comment]
Sorry I cannot test this anymore since we stopped using **RJDBC** in favour of **odbc** at work (at elast without violating IT guidelines). I don't have access to DB2 databases anywhere else.

**Comment by s-u** [comment]
@s-fleck Thanks, I'll close it since NAs are now set as NULLs so it should work. If anyone disagrees they can re-open with details.
