### ISSUE TITLE
Update documentation to accommodate dev version of DBI

### ISSUE THREAD

**Issue by krlmlr** [s-u/RJDBC#54]
Because DBI changes the way it defines some generics, the documentation in *RJDBC* needs to be updated. Unfortunately I don't see a workaround in DBI itself. When checking your package, I'm seeing now:

```
❯ checking for missing documentation entries ... WARNING
  Undocumented S4 methods:
    generic 'dbExistsTable' and siglist 'JDBCConnection,ANY'
    generic 'dbListFields' and siglist 'JDBCConnection,ANY'
    generic 'dbRemoveTable' and siglist 'JDBCConnection,ANY'
    generic 'dbWriteTable' and siglist 'JDBCConnection,ANY'
  All user-level objects in a package (including S4 classes and methods)
  should have documentation entries.
  See chapter ‘Writing R documentation files’ in the ‘Writing R
  Extensions’ manual.
```

Sorry for the inconvenience.

**Comment by lmeninato** [comment]
I agree. It's a bit annoying that typing '?RJDBC::dbGetQuery()' returns a no documentation error.

**Comment by krlmlr** [comment]
Looks like this has been fixed, because the check page doesn't show any errors?

**Comment by s-u** [comment]
Now fixed.
