### ISSUE TITLE
dbWriteTable append fails

### ISSUE THREAD

**Issue by renedlog** [s-u/RJDBC#55]
The problem is, that:
`
dbWriteTable(conn = sqlserver, value = df, name = table, append = TRUE)`
Sucessfully creates a non existing table but overwrites the existing table if called this way.

`dbWriteTable(conn = sqlserver, value = df, name = table, append = TRUE, overwrite = FALSE)`
Results in an error if the table does not already exist. If the table exists it sucessfully appends the data.

So how is it possible to create a table if it not already exists and append the data?
I haven't found a working solution with RJDBC and SQL Server 2017

**Comment by harveyl888** [comment]
One way around could be to test for the existence of the table as follows:

`dbWriteTable(conn = sqlserver, value = df, name = table, append = TRUE, overwrite = !dbExistsTable(sqlserver, table))`

**Comment by s-u** [comment]
We need to adjust the semantics - originally `append` implied that the table must exist since you cannot append to non-existing table, but now `DBI` documents it as "append if you can, create otherwise". Also we should change the defaults, since `overwrite=TRUE` is a bit dangerous.

**Comment by Thinking2018** [comment]
I have the same issue

my example is as follows:

```
# connect to Oracle database 
drv<-JDBC("oracle.jdbc.driver.OracleDriver","ojdbc6_g.jar", identifier.quote="\"")  
conn<-dbConnect(drv,"jdbc:oracle:thin:@localhost:1521:orcl","hr","hr") 

# write data into Oracle
data(iris)
dbWriteTable(conn,"iris1",iris)
# up to now it's fine
```


when I want to append data into the original table, it returns an error message here

```
dbWriteTable(conn,"iris1",iris,append=TRUE)
Error in .local(conn, statement, ...) : 
  execute JDBC update query failed in dbSendUpdate (ORA-00955: 鍚嶇О宸茬敱鐜版湁瀵硅薄浣跨敤
)

```
The error code ORA-00955 is saying that 'name is already used by an existing object'

sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

Matrix products: default

locale:
[1] LC_COLLATE=Chinese (Simplified)_China.936 
[2] LC_CTYPE=Chinese (Simplified)_China.936   
[3] LC_MONETARY=Chinese (Simplified)_China.936
[4] LC_NUMERIC=C                              
[5] LC_TIME=Chinese (Simplified)_China.936    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RJDBC_0.2-8  rJava_0.9-13 DBI_1.1.1   

loaded via a namespace (and not attached):
[1] compiler_4.0.3 tools_4.0.3

**Comment by connorH982** [comment]
Just wanted to add I'm getting the same issue as @Thinking2018. 


dbWriteTable works if a table does not already exist. But if it does, it returns an error. As does dbAppendTable. 

Oddly I am also noticing that if I try dbExistsTable("mytable"), I get FALSE? Maybe its related to not being able to properly detect if a table exists already?

**Comment by BrazilForever11** [comment]
I am connecting to SQL Server and getting the same error:

```
RJDBC::dbWriteTable(conn = conn, name = "Some_scheme.some_table" ,
                  value = df, append = T, overwrite = F)
```


```
Error in .local(conn, statement, ...) : 
  execute JDBC update query failed in dbSendUpdate (There is already an object named 'some_table' in the database.)
Error in .local(conn, statement, ...): execute JDBC update query failed in dbSendUpdate (There is already an object named 'some_table' in the database.)
Error in .local(conn, statement, ...): execute JDBC update query failed in dbSendUpdate (There is already an object named 'some_table' in the database.)
```
