### ISSUE TITLE
Connect JIRA with R

### ISSUE THREAD

**Issue by tusharHoneywell** [s-u/RJDBC#60]
I am not able to connect to JIRA using R. Following are the details which might help you to help me.

R version being used:
R version 3.4.1 (2017-06-30) -- "Single Candle"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

Installed package RJDBC. I get following output after loading the library

library('RJDBC')  
Loading required package: DBI
Loading required package: rJava
Warning messages:
1: package ‘RJDBC’ was built under R version 3.4.4
2: package ‘DBI’ was built under R version 3.4.4
3: package ‘rJava’ was built under R version 3.4.3

Installed and loaded cdata

library('cdata')
Loading required package: wrapr
Warning messages:
1: package ‘cdata’ was built under R version 3.4.4
2: package ‘wrapr’ was built under R version 3.4.4

How do I remove below error?

driver <- JDBC(driverClass = "cdata.jdbc.jira.JiraDriver", classPath = "MyInstallationDir//lib//cdata.jdbc.jira.jar", identifier.quote = "'")
Error in .jfindClass(as.character(driverClass)[1]) : class not found

**Comment by karillo** [comment]
This looks like a direct implementation of the kB article at https://www.cdata.com/kb/tech/jira-jdbc-r.rst

I would think the most obvious cause of this result is that the path listed doesn’t point to the actual jar files (since it's unlikely you’re actually using a folder called `MyInstallationDir` for your deployment). 

Perhaps try the absolute path to the file rather than a path relative to where you’re invoking your R session.

**Comment by tusharHoneywell** [comment]
Agree. Directory does not exist. I installed cdata package using R and I do not see any jar file in my system after installing like, install.packages('cdata') or RJDBC

Moreover, I have not created any JIRADriver. Is it not required? The way we do to create any ODBC connection via windows.

**Comment by karillo** [comment]
Im not sure there’s any relationship between cdata.com and https://winvector.github.io/cdata/ 

The driver (trial or licensed) downloaded from https://www.cdata.com/drivers/jira/download/ wouldn’t be installed as part of your R libraries. You would have installed it somewhere else.

**Comment by tusharHoneywell** [comment]
Thanks. That is where I got misled. Do you know how can i connect to JIRA Atlassian tool using R?
