### ISSUE TITLE
Labels instead Names in results

### ISSUE THREAD

**Issue by VictorYammouni** [s-u/RJDBC#61]
Hello

in "fetch" method, you use the getColumnLabel function to get the columns names. So, sometime, it returns dataframes with complex columns names.

in this case, the getColumnName function is'nt more suitable ?

Regards

**Comment by VictorYammouni** [comment]
Hello,

is this behavior definitive?
is there a way to add an option to have names instead of labels?

PS : Sorry, I posted this message in another place

Thank's

**Comment by dernst** [comment]
It seems you get the names from a result set via `dbColumnInfo`:
https://github.com/s-u/RJDBC/blob/master/R/class.R#L354

**Comment by s-u** [comment]
This has now been addressed as part of #74
