### ISSUE TITLE
dbReadTable says “invalid object name” but can select from with dbGetQuery

### ISSUE THREAD

**Issue by ahood** [s-u/RJDBC#62]
The following code fails at the second to last line but retrieves the correct result set on the last line:

```
library(RJDBC)
drv <- JDBC("com.microsoft.sqlserver.jdbc.SQLServerDriver","D:/sqljdbc4.jar")
conn <- dbConnect(drv, 
  'jdbc:sqlserver://[servername];databaseName=[databasename]',
  '[username]', '[password]'
)

new_records_table <- 'dbo.new_dummy'
try(dbRemoveTable(conn, new_records_table), silent=T) # in case the table was already there
input_table <- data.frame(col1=c('A'))
dbWriteTable(conn, new_records_table, input_table)

dbReadTable(conn, new_records_table) # fails
dbGetQuery(conn, paste('SELECT * FROM', new_records_table)) # succeeds
```

(where [servername], [databasename], [username], and [password] were suppressed).

The error at the second to last line is
```
Error in .verify.JDBC.result(r, "Unable to retrieve JDBC result set for ",  : 
  Unable to retrieve JDBC result set for SELECT * FROM "dbo.new_dummy" (Invalid object name 'dbo.new_dummy'.)
```
If I do `dbReadTable(conn, 'new_dummy')` instead, then there is no error and the correct result is retrieved. However, the problem remains for tables part of a non-dbo schema.

I'm on Windows 7 64-bit using R version 3.5.1, and output from sessionInfo() shows "RJDBC_0.2-7.1", "rJava_0.9-10", and "DBI_1.0.0" as the other attached packages. For the SQL server, it's SQL Server 2016.

**Comment by s-u** [comment]
This is actually a bug in DBI - the full output is actually:

```
Note: method with signature ‘DBIConnection#character’ chosen for function ‘dbReadTable’,
 target signature ‘JDBCConnection#character’.
 "JDBCConnection#ANY" would also be valid
```

As you can see it was overriding our implementation with one that use invalid SQL syntax. I have added a work-around in 18953dc so our method is now used. Also note that you may have to specify the character used for quoting in your DBMS  depending on the names you use (see the documentation).
