### ISSUE TITLE
How do I automatically find available JDBC drivers?

### ISSUE THREAD

**Issue by MCM-Math** [s-u/RJDBC#65]
I'm developing code for others to use, and they don't all have the same setup.  Is it possible to have R find, and possibly choose a JDBC driver to use?

**Comment by dernst** [comment]
`RJDBC` uses the JVM to find JDBC drivers, which means they need to be added to the classpath. You can set the `CLASSPATH` environment variable or manually use `.jaddClassPath`.  As far as I can tell you'll have to supply that information by yourself. Perhaps you can use some heuristic in your code which, depending on OS/hostname/whatever adds all drivers from a specific folder:
```
.jaddClassPath(list.files(path = "some/folder", pattern="\\.jar$", recursive=TRUE))
```
I'd probably rather make wrapper functions to connect to certain databases which also loads the correct drivers. But not sure what kind of automation you're looking for and what the restrictions are.

**Comment by s-u** [comment]
There is no generic way to find drivers as there is no canonical location whether they would be installed.
