### ISSUE TITLE
FR: javaGC() for clearing Java heap

### ISSUE THREAD

**Issue by MichaelChirico** [s-u/RJDBC#66]
It's not uncommon for me to get eyes to big for my laptop's stomach and try to `dbGetQuery` some table that's too big for `rJava` to handle (as configured).

Usually it's the case then that the Java heap gets a bit clogged up and could benefit from a `gc()`; I recently came upon [this Q&A](https://stackoverflow.com/q/12476044/3576984) about how to `gc()` specifically on the Java side; it could be useful to expose a helper function in `RJDBC` to handle this like

```
javaGC = function(...) {
  gc(...)
  rJava::J("java.lang.Runtime")$getRuntime()$gc()
  return(invisible())
}
```

For my own purposes, I'm writing a package that currently has an `RJDBC` import but no direct `rJava` import -- could avoid cluttering the `DESCRIPTION` a bit more if I can `importFrom` `RJDBC` instead of `rJava`. 

But I do think that this operation is common enough for `RJDBC` use cases specifically that exposing this helper here makes sense.

Happy to file a PR if you think it's useful.

**Comment by s-u** [comment]
This may be actually more useful in rJava since it has nothing to do with RJDBC.

**Comment by MichaelChirico** [comment]
Filed https://github.com/s-u/rJava/issues/180

**Comment by s-u** [comment]
Thanks!
