### ISSUE TITLE
regular expression in hive query

### ISSUE THREAD

**Issue by Chandrak1907** [s-u/RJDBC#67]
I am trying to use regular expression to select few columns from hive table.  Example code is below:

> 
> q1= "set hive.support.quoted.identifiers= none;"
>  dbSendQuery(conn,q1)
> Error in .verify.JDBC.result(r, "Unable to retrieve JDBC result set for ",  : 
>   Unable to retrieve JDBC result set for set hive.support.quoted.identifiers= none; (Error while processing statement: 'SET hive.support.quoted.identifiers=none;' FAILED in validation : Invalid value.. expects one of [none, column].)

> q2="select concat('M',MB.mem), MB.`(mem)?+.+` from db.table as MB"
> SemanticException [Error 10002]: Line 1:36 Invalid column reference '(mem)?+.+')

**Comment by dernst** [comment]
Maybe the first statement fails because there's a trailing semicolon (;) after `none`? Otherwise I don't see how this is an `RJDBC` problem.

Also for code blocks use triple backticks like so:
```
q1= "set hive.support.quoted.identifiers= none;"
dbSendQuery(conn,q1)
Error in .verify.JDBC.result(r, "Unable to retrieve JDBC result set for ", :
Unable to retrieve JDBC result set for set hive.support.quoted.identifiers= none; (Error while processing statement: 'SET hive.support.quoted.identifiers=none;' FAILED in validation : Invalid value.. expects one of [none, column].)
```
```
q2="select concat('M',MB.mem), MB.(mem)?+.+ from db.table as MB"
SemanticException [Error 10002]: Line 1:36 Invalid column reference '(mem)?+.+')
```

**Comment by s-u** [comment]
Note that the first one is not a query so should use `dbSendUpdate()` instead. But I agree, this is a HSQL question since hive is complaining about the syntax not JDBC.
