### ISSUE TITLE
Unable to retrieve JDBC tables list

### ISSUE THREAD

**Issue by shreyas2290** [s-u/RJDBC#69]
I am trying to upload a dataframe to presto server. It is showing the following error:
"Error in .verify.JDBC.result(r, "Unable to retrieve JDBC tables list") : Unable to retrieve JDBC tables list ()"
Code Used:
dbWriteTable(conn,DBI::SQL("test.demo"),value = df)
I have also tried using insert into, create, drop commands in dbSendQuery with the same connection and it is working perfectly. I am facing issue when I use dbWriteTable function.
I have tried other functions of the DBI package like dbReadTable, dbCreateTable too which is working perfectly for me.
Please help!

**Comment by s-u** [comment]
The table name must be a string, did you try `dbWriteTable(conn,"test.demo",df)`?

**Comment by shreyas2290** [comment]
Yes, I tried that as well

**Comment by s-u** [comment]
Closing for lack of details. Please re-open with full output and reproducible example if it still persists.
