### ISSUE TITLE
Session being terminated

### ISSUE THREAD

**Issue by kafran** [s-u/RJDBC#75]
I'm using RJDBC with TEIID JDBC Driver. I'm running a query which returns a very big result. When I start Fetching the result, after a while (10~15%) I get an error telling the sessions could already been terminated: `org.teiid.client.security.InvalidSessionException TEIID40042 Invalid Session Session may have already been terminated`.

Reading the documentation I found this:

> Note that the life time of a connection, result set, driver etc. is determined by the lifetime of the corresponding R object. Once the R handle goes out of scope (or if removed explicitly by rm) and is garbage-collected in R, the corresponding connection or result set is closed and released. This is important for databases that have limited resources (like Oracle) - you may need to add gc() by hand to force garbage collection if there could be many open objects. The only exception are drivers which stay registered in the JDBC even after the corresponding R object is released as there is currently no way to unload a JDBC driver (in RJDBC).

Is this related? How can I work around this?

I think the guilt could be the SQLite, since I was catching the results and saving it to a local database, I think the long I/O could have made me lost the session. But I also have a suspect that this could be R's fault. An ugly solution was to disconnect and reconnect to the database in each batch.

```
[...]

for(date in dates) {
  # Creates a new connection
  conn <- RJDBC::dbConnect(drv, "jdbc:teiid:Database@mms://host:31000;FetchSize=400000", user = Sys.getenv('user'), password = Sys.getenv('pwd'))
  
  # Send the parameterized query to the DB
  res <- RJDBC::dbSendQuery(conn, querys, date[1], date[2])
  cat("From ", date[1], " to ", date[2], "\n")
  
  # Fetches 400.000 lines
  while(1) {
    fetch_res <- RJDBC::fetch(res, n = 400000)
    cat(nrow(fetch_res), "rows fetched\n")
  
    # Ends the connection
   # Removes the R objects
    if(nrow(fetch_res) == 0) {
      RJDBC::dbClearResult(res)
      RJDBC::dbDisconnect(connSiasgDW)
      rm('conn', 'res')
      break;
    }

    # Saves the batch result to the SQLite
    if(RSQLite::dbExistsTable(conSQLite, "table")) {
      RSQLite::dbAppendTable(conSQLite, "table", fetch_res)
    } else {
      RSQLite::dbWriteTable(conSQLite, "table", fetch_res)
    }
  }
}

[...]
```

**Comment by s-u** [comment]
You'll have to refer to your DMBS/driver. R won't terminate anything as long as you have references, which you do in your code, so it's not initiated from the R side. Maybe a timeout in the database?
