### ISSUE TITLE
This week dbconnect stopped working

### ISSUE THREAD

**Issue by wilson-camargo-jr** [s-u/RJDBC#76]
This week, RJDBC stopped working in both linux and windows SO. The code was working fine las week but now I got the error when trying to open a connection to a DB2 Database.

R Version 3.6.1
RJDBC 0.2-7.1
rJava 0.9-11

Error in .jcall(p, "Ljava/lang/Object;", "setProperty", "password", password) : 
  method setProperty with signature (Ljava/lang/String;D)Ljava/lang/Object; not found

**Comment by shruti-par** [comment]
I am facing the same issue. Were you able to resolve it?

**Comment by s-u** [comment]
The error suggests that you're using a numeric vector instead of a string as password. Make sure you don't forget the quotes or use `as.character()`
