### ISSUE TITLE
dbWriteTable fails on Athena due to type translation

### ISSUE THREAD

**Issue by ras44** [s-u/RJDBC#79]
I am able to create an RJDBC connection to AWS Athena and can successfully execute `dbListTables` and `dbGetQuery`, however when I attempt to create a table with:

```
df_test <- data.frame(a=1)
dbWriteTable(conn,"athena_scratch.username_tmp_df_test",df_test,overwrite=T)
```
I receive the following error:
```
Error in .local(conn, statement, ...) : 
  execute JDBC update query failed in dbSendUpdate ([Simba][AthenaJDBC](100071) An error has been thrown from the AWS Athena client. line 1:62: no viable alternative at input 'CREATE TABLE athena_scratch.xxxxxxxxxx_tmp_df_test (a DOUBLE PRECISION' [Execution ID not available])
```
It appears the "PRECISION" is incorrectly being used as part of the type definition.  I'm not sure if this is an issue with RJDBC or the driver.

When I change the test datatype to a string, the error does not arise:
```
df_test <- data.frame(a="test")
dbWriteTable(conn,"athena_scratch.username_tmp_df_test",df_test,overwrite=T)
```

Data types are listed here: https://docs.aws.amazon.com/athena/latest/ug/create-table.html

Thanks for your advice

**Comment by dernst** [comment]
ANSI SQL and SQL92 both seem to define a `DOUBLE PRECISION` data type. Why Athena does not understand while claiming to support ANSI SQL I cannot say.

Anyway you could try using ODBC alongside the `odbc` R package which is more actively maintained and faster.
https://docs.aws.amazon.com/athena/latest/ug/connect-with-odbc.html

Alternatively you could write your SQL by hand to avoid Athena-specific problems.

**Comment by s-u** [comment]
definitely a bug in the driver/DB - the standard is very clear: 

    SQL defines distinct data types named by the following <key word>s:
    CHARACTER, CHARACTER VARYING, BIT, BIT VARYING, NUMERIC, DECIMAL,
    INTEGER, SMALLINT, FLOAT, REAL, DOUBLE PRECISION, DATE, TIME,
    TIMESTAMP, and INTERVAL.

But `dbWriteTable` is just syntax sugar for `CREATE TABLE` + `INSERT` so non-standard databases should just use that.
