### ISSUE TITLE
Cannot send 'SET' commands to Hive over JDBC

### ISSUE THREAD

**Issue by suprtomato** [s-u/RJDBC#88]
Although a bare 'SET' command can execute in hive using sendQuery, it appears that the attempt to validate the 'SET' statements to actually set a variable is failing either when using dbSendStatement or dbSendUpdate methods.  An example would be 'SET hive.cbo.enable=true;'.

If I run just these two commands, the SQL does execute and subsequent bare 'SET' commands show the update expected.
```
s <- .jcall(con@jc, "Ljava/sql/Statement;", "createStatement")
.jcall(s, "I", "executeUpdate", SQL, check=FALSE)
```
Original Debug:
Message: Error in .jcall(conn@jc, "Ljava/sql/Statement;", "createStatement") :
RcallMethod: attempt to call a method of a NULL object.
Available environments had calls:
1: DBI::dbSendStatement(con, SQL)
2: DBI::dbSendStatement(con, SQL)
3: dbSendQuery(conn, statement, ...)
4: dbSendQuery(conn, statement, ...)
5: .local(conn, statement, ...)
6: .jcall(conn@jc, "Ljava/sql/Statement;", "createStatement")

**Comment by s-u** [comment]
This looks more like  a problem with your driver - you don't even have a valid connection to the database (your connections is `NULL` according to the error). Are you sure you're connected? Please don't post hypotheses, provide exact code and output of the code that fails.

**Comment by suprtomato** [comment]
You are correct, the behavior was not repeatable.  Sorry for the distraction.
