### ISSUE TITLE
Methods for `dbIsValid()`

### ISSUE THREAD

**Issue by mikkmart** [s-u/RJDBC#89]
I'd like to test if a `JDBCConnection` has been disconnected. In my understanding, `dbIsValid()` would be the `DBI` generic to use. However, `RJDBC` doesn't implement any methods for it.

I'm no expert with JDBC, but I've added a workaround for `JDBCConnection` to my script which seems to get the job done:

``` r
setMethod("dbIsValid", "JDBCConnection", def = function(dbObj, ...) {
  !.jcall(dbObj@jc, "Z", "isClosed")
}, valueClass = "logical")
```

It would be great to see `dbIsValid()` supported by `RJDBC` out-of-the-box.

**Comment by s-u** [comment]
Thanks, that's a good idea, now added. I have not been following all the new methods DBI has introduced recently so if there are more useful ones, feel free to add them to issues.

**Comment by mikkmart** [comment]
Thank you so much, I really appreciate it!

I tested the new method, but unfortunately it errors out for me:

``` r
dbIsValid(conn)
#> Error in .jcall(dbObj@jc, "Z", "isValid", as.integer(timeout)[1]) : 
#>   java.lang.AbstractMethodError: Method com/sas/net/sharenet/ShareNetConnection.isValid(I)Z is abstract
```

Looks like my driver (SAS/SHARE for JDBC) doesn't implement the `Connection.isValid` method. I assume this is really an issue to be addressed with the driver itself, but to be honest I don't have high hopes of that happening.

Would you have any advice on how to deal with this?

**Comment by s-u** [comment]
Wow, that is indeed a problem. Drivers not implementing an API method is truly a no-no. `isValid()` was introduced in JDBC 2.0 for JDK 1.6 in 2006, so if SAS wasn't able to fix it in 15 years, I don't see it being fixed anytime soon, either.

I have added a work-sound that uses `isClosed()` instead on error. Please give it a try and let me know if it works for you since I have no way to test it.

**Comment by mikkmart** [comment]
Thanks again! I tried it out and can confirm that it's working as expected now. 🎉
