### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by lmlicuanan** [s-u/RJDBC#98]
When an error is encountered I need to interrupt the process myself because it doesn't exit on its own, which prevents me from creating automated retry flows. Calling a dbGetQuery here with redshift:

<img width="604" alt="image" src="https://user-images.githubusercontent.com/52149230/189785318-caf97e0a-faac-4f13-b9ab-7dd28e4be4a9.png">

Hoping the team can force these hanging processes to terminate so I can set up robust error handling. Or suggest ways to get around it if there are any best practices. Thanks!

**Comment by s-u** [comment]
@lmlicuanan What you are posing is terribly incomplete - please paste (do not use screenshots!) the __full error__ (both Java and R) as well as the entire code you're running since the may be equally an issue in your code or the driver or anything else - but without full output it's hard to see what you are asking about. All we know is that something broke in the RedShift driver, but we don't even know what is the "process" you're talking about, what is the platform, what code is being run etc.

**Comment by lmlicuanan** [comment]
Hi @s-u apologies for that, hope this clarifies:

```
redshift_query <- function(.sql, ...) {
  # .sql here is a sql file
  # https://aws.amazon.com/blogs/big-data/connecting-r-with-amazon-redshift/
  suppressPackageStartupMessages({
    library(dplyr)
    library(glue)
    library(DBI)
    library(RJDBC)
    library(pool)
    library(readr)
  })
  
  Sys.sleep(2)
  
  message(glue("{Sys.time()} Connecting to DB..."))
  driver <- JDBC(
    "com.amazon.redshift.jdbc41.Driver", 
    "RedshiftJDBC41-1.1.9.1009.jar", 
    identifier.quote="`"
  )
  url <- glue(
    "jdbc:redshift://127.0.0.1:5439/",
    "prod?user={Sys.getenv('REDSHIFT_USERNAME')}&",
    "password={Sys.getenv('REDSHIFT_PASSWORD')}"
  )
  conn <- dbPool(drv = driver, url = url, minSize = 1, maxSize = 2)
  
  message(glue("{Sys.time()} Querying..."))
  sql <- sqlInterpolate(conn, read_file(.sql), ...)
  df <- dbGetQuery(conn, sql) %>% as_tibble()
  
  message(glue("{Sys.time()} Closing DB connection..."))
  poolClose(conn)
  
  message(glue("{Sys.time()} Success!"))
  return(df)
}

redshift_query(path_to_file)
```

I'm confident this function works, but I do occasionally get this error message.

```
2022-09-13 11:21:51 Connecting to DB...
2022-09-13 11:21:52 Querying...
java.lang.ArrayIndexOutOfBoundsException: 7630744
        at com.amazon.redshift.api.PGDataTypeUtilities.toInt(Unknown Source)
        at com.amazon.redshift.client.messages.inbound.DataRow.buildColumnIndexes(Unknown Source)
        at com.amazon.redshift.client.messages.inbound.DataRow.getColumnBeginIndex(Unknown Source)
        at com.amazon.redshift.dataengine.PGResultSet.getData(Unknown Source)
        at com.amazon.jdbc.common.SForwardResultSet.getData(Unknown Source)
        at com.amazon.jdbc.common.SForwardResultSet.getString(Unknown Source)
        at com.amazon.redshift.core.jdbc41.PGJDBCS41ForwardResultSet.getString(Unknown Source)
        at info.urbanek.Rpackage.RJDBC.JDBCResultPull.fetch(JDBCResultPull.java:107)
```

I don't know what the root cause (having zero familiarity with java and only a rudimentary understanding of DBs) is, but it typically just resolves itself upon rerunning.

The current behavior though is the run only quits if I interrupt it myself, i.e. it displays this message but doesn't error out. I think the ideal behavior is that it does quit by itself, so that I can set up retry flows.

Thanks and hope this is enough to go on

**Comment by lmlicuanan** [comment]
No worries @s-u thank you for investigating and the tips. I will take a second look and close this issue for now
