### ISSUE TITLE
RJDBC uses old dbplyr interface

### ISSUE THREAD

**Issue by mw-stanley** [s-u/RJDBC#99]
Using RJDBC (v0.2-10) connections with dbplyr results in a warning:

```
> some_table <- tbl(con, "some_table")
Warning message:
<JDBCConnection> uses an old dbplyr interface
ℹ Please install a newer version of the package or contact the maintainer
```

I believe this relates to dbplyr's 2.0.0 backend and there is some documentation about this here: https://dbplyr.tidyverse.org/articles/backend-2.html

**Comment by s-u** [comment]
RJDBC has absolutely nothing to do with `dplyr`, so it's likely a bug in some other package (or `dplyr` itself).
